version: '3.7'

services:
  currency-exchange:
    image: cozmus/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
    - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411/

  currency-conversion:
    image: cozmus/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411/

  api-gateway:
    image: cozmus/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411/

  naming-server:
    image: cozmus/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network

networks:
  currency-network: